version: '3.8'
services:
  etap:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imex12345/0.
      POSTGRES_DB: etap
    networks:
      - etapinsure
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imex12345/0.
      POSTGRES_DB: etap
    networks:
      - etapinsure
networks:
  etapinsure: